###
GET http://localhost:3000/api/contacts

###
GET http://localhost:3000/api/contacts/drsAJ4SHPYqZeG-83QTVW

###
DELETE http://localhost:3000/api/contacts/70ca69b3-535f-4d5f-aa42-5b1902ec7db5

###
POST http://localhost:3000/api/contacts
Content-Type: application/json

{
    "name": "Mariana Myfin",
    "email": "msdfr@git.com",
    "phone": "+349812987333"
}

###
PUT http://localhost:3000/api/contacts/AeHIrLTr6JkxGE6SN-0Rw
Content-Type: application/json

{
    "name": "Kennedy Lane Updated",
    "email": "kennedy.updated@example.com"
}